version: '3.8'

services:

  db:
    image: postgres:15.3-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes: 
      - ./db-data:/var/lib/postgresql/data

